### PR TITLE
Looked into enabling timing out dialling.

### PR DESCRIPTION
**Pull request by micrypt**

### CODE REVIEW

**Comment by fiorix** [comment]
Looks fine, would you do it for TLS too?

**Comment by micrypt** [comment]
Sure thing. I'll sort that out tonight.

**Comment by fiorix** [comment]
Any word here?

**Comment by fiorix** [comment]
Maybe you @jaroszan ?

**Comment by micrypt** [comment]
@fiorix I wasn't certain what API to use for this, as the `net` package doesn't expose a `DialSSLTimeout` but rather requires using a client within the `tls` package. Consequently, I was a bit tad as to what's preferable. Would a separate client be better, or a design that's inconsistent with the Go standard library?

**Comment by fiorix** [comment]
It's all on `crypto/tls`. You can choose between `Client(netConn, tlsConfig)`, or `Dial`, or `DialWithDialer`.

**Comment by micrypt** [comment]
@fiorix Perhaps I was unclear… The question is not the means to implement it, but how (design-wise). Would it be okay to just add a `DialSSLTimeout` on `sm.Client`?

**Comment by fiorix** [comment]
Yeah, both `DialTimeout` and `DialTLSTimeout` on both packages `diam` and `diam/sm` I would think.

**Comment by jaroszan** [comment]
@fiorix: I'll check the related issue, but it looks that micrypt is already on top of it :)

**Comment by fiorix** [comment]
Alright, both #50 and #60 merged. Thanks @micrypt and @jaroszan!

**Comment by micrypt** [comment]
Thanks, @jaroszan!

**Pull request merged**
