### PR TITLE
fix-time-reflection

### PR DESCRIPTION
**Pull request by jaroszan**

### CODE REVIEW

**Comment by jaroszan** [comment]
It seems that nothing was broken and datatype.Time is correctly unmarshalled. 

There is still an issue with time zones, I will look into it.

Should address https://github.com/fiorix/go-diameter/issues/64

**Comment by fiorix** [comment]
That's cool. Should be easy to fix the timezone thing, and also (very important) to support not only `datatype.Time` but also `time.Time` for ease of use of the unmarshaller.

**Comment by DefunctExodus** [comment]
This is really great.

**Comment by jaroszan** [comment]
So far datatype.Time works, I will add tests to check if time.Time is properly unmarshalled and look into it as well.

**Comment by fiorix** [comment]
👍

**Comment by jaroszan** [comment]
Both time.Time and time.Datatype look ok now with tests. Will look into timezones next.

**Comment by fiorix** [comment]
Amazing. I like the diff so far.

**Comment by jaroszan** [comment]
Thanks, reflecting was quite tricky, I didn't do it before.

Should be good for review now. Time for both types is converted to UTC before checking against expected time.

**Comment by fiorix** [comment]
Reflection is a bit tricky to wrap your head around, but I'm happy that you did it yourself and also learned from it.

**Comment by fiorix** [comment]
Should we have a test that is not in UTC time, to ensure we can actually parse it correctly?

**Comment by jaroszan** [comment]
Do you mean using `time.LoadLocation` ?

If I understand correctly we are receiving time and formatting it as we please (and some baseline is needed since we run tests in different timezones and travis uses UTC). If you have something specific in mind let me know and I'll look into it.

**Comment by fiorix** [comment]
What I'm saying is to have a test that has the timezone different than UTC, preferably some weird timezone such as those with half hour offset, and ensure we parse it correctly to the equivalent UTC time. For instance we could have a test to parse the Bangaluru (India) timezone, which is UTC+5:30.

**Comment by jaroszan** [comment]
I am confused, please correct me if I am wrong:

1. According to RFC 6733, time datatype uses NTP format and is tied to UTC
2. Hence time that we get from the wire is always UTC, it's not possible to get NTP time with an offset
3. Zone/offset matters when we examine time locally so it's only a question of formatting UTC time received from the network

**Comment by fiorix** [comment]
Nevermind. :)

**Pull request merged**
