### PR TITLE
Go diameter S6a support tests & bug fixes

### PR DESCRIPTION
**Pull request by emakeev**
Go-Diameter fix for possible deadlocking in close notifier, additional S6a commands (CL), examples & unit tests

### CODE REVIEW

**Comment by emakeev** [comment]
travis fix

**Comment by fiorix** [comment]
hey I think some of these commits were merged already.. you probably have to rebase to master

**Comment by emakeev** [comment]
Rebased...

**Comment by fiorix** [comment]
👍

**Pull request merged**
