### PR TITLE
fix panic in avp.DecodeFromBytes

### PR DESCRIPTION
**Pull request by 0rac1e**
in some cases method crashes with panic. Extra length check added.

panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/fiorix/go-diameter/diam.(*AVP).DecodeFromBytes(0xc003185d40, 0xc002f862a8, 0x28, 0x158, 0x4, 0xc0000a4050, 0x3, 0x800000c002686480)
        /go/src/github.com/fiorix/go-diameter/diam/avp.go:74 +0x5b1
github.com/fiorix/go-diameter/diam.DecodeAVP(0xc002f862a8, 0x28, 0x158, 0x4, 0xc0000a4050, 0xc002686480, 0x8, 0x10)
        /go/src/github.com/fiorix/go-diameter/diam/avp.go:45 +0x74
github.com/fiorix/go-diameter/diam.DecodeGrouped(0xc002f861f0, 0xe0, 0x210, 0x4, 0xc0000a4050, 0xc000389400, 0x0, 0x0)
        /go/src/github.com/fiorix/go-diameter/diam/group.go:29 +0xfc
github.com/fiorix/go-diameter/diam.(*AVP).DecodeFromBytes(0xc003185b00, 0xc002f861e4, 0xec, 0x21c, 0x4, 0xc0000

### CODE REVIEW

**Comment by fiorix** [comment]
I'm surprised this check isn't elsewhere. Perhaps there's something else going on here. Where does 12 come from?

Tests are failing, cannot proceed before tests pass.

**Comment by 0rac1e** [comment]
panic occurs on line 71/74 avp.go
`payload = data[12:]`/`payload = data[8:]` - 12 comes from here
 when 
`a.Length = int(uint24to32(data[5:8])) // returns 1 in my case`

I think data given to DecodeFromBytes method is not valid.

**Comment by 0rac1e** [comment]
Travis stucks on
=== RUN TestHandleCER_HandshakeMetadataTCP-2

**Comment by fiorix** [comment]
Good catch, thanks!

**Pull request merged**
