### PR TITLE
update server.go to handle CER and DWR correctly

### PR DESCRIPTION
**Pull request by jaroszan**
- Added OnDWR handler
- Set Origin-State-Id to be optional in CER, as specified in rfc6733, section 5.3.1

### CODE REVIEW

**Comment by fiorix** [comment]
I've added a couple of comments to this change, please take a look.

**Comment by jaroszan** [comment]
Updated according to your suggestions, details in the commit.

**Comment by fiorix** [comment]
You need a `sync.Mutex` to guard the `allowedPeers` map since concurrent access to that map will cause trouble. Go has optimizations for empty structs for those and other cases, thus make it `allowedPeers map[string]struct{}` to save some resources.

Also, you're never deleting from that map when the client disconnect. In order to do that you have to watch for disconnect events in a separate goroutine. You can do `<-c.(CloseNotifier).CloseNotify()` to block until a client disconnects, and when that happen you remove it from the map. :)

**Comment by jaroszan** [comment]
As previously details in the commit :)

**Comment by jaroszan** [comment]
Given that this example will soon be no longer valid I guess it should be closed without merging. Still it was interesting to me from educational perspective, thanks for the hints :)

**Pull request closed without merging**
