### PR TITLE
removed dependency on parser for supported apps verification

### PR DESCRIPTION
**Pull request by jaroszan**
This one has the following goals:
- fix error message to user when client is initialized with apps unsupported locally (an issue introduced in https://github.com/fiorix/go-diameter/pull/56 and mentioned in https://github.com/fiorix/go-diameter/issues/61) - can be fixed by other means but current one seems natural
- make use of sm.supportedApps which is used for supported apps verification on the server side

It has 2 potential downsides:
- sm and sm client can be initialized with different dictionaries (however it does not seem likely)
- fmt dependency is added (though it makes it possible to generate very descriptive message to library user )

### CODE REVIEW

**Comment by jaroszan** [comment]
Ok, will have to fix some smparser tests.

**Comment by jaroszan** [comment]
TestClient_Dial_MissingApplication is removed since it looks like it doesn't account for that Auth-Application-Id and Acct-Application-Id are optional. 

Can you please review this one?

**Comment by fiorix** [comment]
👍 

Let me know if you're done or if there's more to this one.

**Comment by jaroszan** [comment]
Looks done now. There is an extra fix for TestCEA not connected to this PR (it didn't make sense to open separate PR)

**Comment by fiorix** [comment]
Excellent, thanks!

**Pull request merged**
