### PR TITLE
FindAVPWithVendor

### PR DESCRIPTION
**Pull request by danbogos**
With tests and golint.

DanB

### CODE REVIEW

**Comment by fiorix** [comment]
Still failing the tests

**Comment by danbogos** [comment]
Ok wil check.

DanB
Am 02.12.2015 14:48 schrieb "Alexandre Fiori" <notifications@github.com>:

**Comment by danbogos** [comment]
OK, this time should do.

Thanks,
DanB

**Comment by fiorix** [comment]
Great, thanks!

**Pull request merged**
